export const ALL_BRANDS: string[] = [
  "sony",
  "samsung",
  "apple",
  "oneplus",
  "xiaomi",
  "redmi",
  "poco",
  "realme",
  "vivo",
  "oppo",
  "iqoo",
  "nothing",
  "google",
  "motorola",
  "nokia",
  "honor",
  "huawei",
  "infinix",
  "tecno",
  "lava",
  "jbl",
  "boat",
  "noise",
  "bose",
  "sennheiser",
  "marshall",
  "audio-technica",
  "skullcandy",
  "shure",
  "akg",
  "dell",
  "hp",
  "lenovo",
  "asus",
  "acer",
  "msi",
  "lg",
  "tcl",
  "hisense",
  "toshiba",
  "panasonic",
  "philips",
  "dyson",
  "canon",
  "nikon",
  "gopro",
  "dji",
  "fujifilm",
  "amazfit",
  "fitbit",
  "garmin",
  "tp-link",
  "netgear",
  "d-link",
];

export const BRAND_ALIASES: Record<string, string> = {
  "poco": "poco",
  "redmi": "xiaomi",
  "xiaomi": "xiaomi",
  "oneplus": "oneplus",
  "realme": "realme",
  "iqoo": "iqoo",
  "vivo": "vivo",
  "oppo": "oppo",
  "infinix": "infinix",
  "tecno": "tecno",
  "honor": "honor",
  "huawei": "huawei",
  "samsung": "samsung",
  "apple": "apple",
  "google": "google",
  "motorola": "motorola",
  "nokia": "nokia",
  "nothing": "nothing",
  "lava": "lava",
  "sony": "sony",
  "jbl": "jbl",
  "boat": "boat",
  "noise": "noise",
  "bose": "bose",
  "sennheiser": "sennheiser",
  "marshall": "marshall",
  "dell": "dell",
  "hp": "hp",
  "lenovo": "lenovo",
  "asus": "asus",
  "acer": "acer",
  "msi": "msi",
  "lg": "lg",
  "canon": "canon",
  "nikon": "nikon",
  "gopro": "gopro",
  "dji": "dji",
  "panasonic": "panasonic",
  "philips": "philips",
  "dyson": "dyson",
};

import type { ProductCategory } from "../types.ts";

export type { ProductCategory };

export const CATEGORY_KEYWORDS: Record<ProductCategory, string[]> = {
  headphone: [
    "headphone",
    "headphones",
    "over-ear",
    "over ear",
    "on-ear",
    "on ear",
    "wh-",
    "wired headphone",
  ],
  earbuds: [
    "earbuds",
    "earphones",
    "tws",
    "true wireless",
    "in-ear",
    "wf-",
    "buds",
    "airpods",
  ],
  phone: [
    "phone",
    "smartphone",
    "handset",
    "android",
    "iphone",
    "realme",
    "samsung galaxy",
    "oneplus nord",
    "pixel",
    "poco",
    "redmi",
    "iqoo",
    "vivo",
    "oppo",
    "infinix",
    "tecno",
    "lava",
    "nokia",
    "motorola",
    "honor",
    "nothing phone",
    "galaxy s",
    "galaxy a",
    "galaxy m",
    "galaxy f",
    "galaxy z",
    "galaxy note",
    "redmi note",
    "redmi a",
    "redmi b",
    "oneplus",
  ],
  laptop: [
    "laptop",
    "notebook",
    "macbook",
    "chromebook",
    "thinkpad",
    "ideapad",
    "vivobook",
    "pavilion",
    "envy",
    "inspiron",
    "latitude",
    "nitro",
    "predator",
    "tuf gaming",
    "rog",
    "victus",
    "omen",
  ],
  tablet: ["tablet", "ipad", "tab", "pad"],
  watch: ["watch", "smartwatch", "band"],
  camera: ["camera", "dslr", "mirrorless", "gopro", "action cam"],
  tv: ["tv", "television", "smart tv", "monitor"],
  generic: [],
};

export const ACCESSORY_KEYWORDS: string[] = [
  "case",
  "cover",
  "charger",
  "cable",
  "adapter",
  "protector",
  "guard",
  "strap",
  "stand",
  "holder",
  "mount",
  "pouch",
  "sleeve",
  "skin",
  "sticker",
  "decal",
  "tempered",
  "film",
  "armband",
  "holster",
  "silicone",
  "headband",
  "earpad",
  "earpads",
  "tips",
  "foam",
  "replacement",
  "pouches",
  "sleeves",
  "power bank",
  "cooling pad",
  "laptop bag",
  "tripod",
  "memory card",
  "gimbal",
  "lens",
  "amplifier",
  "amplifiers",
  "dac",
  "amp",
  "belt clip",
  "screen guard",
  "back cover",
  "flip cover",
  "ring holder",
  "pop socket",
  "desk stand",
  "wall mount",
  "car mount",
  "selfie stick",
  "ring light",
  "flash drive",
  "usb hub",
  "mouse pad",
  "keyboard cover",
  "palm rest",
  "ssd enclosure",
  "hard drive",
  "webcam",
  "microphone",
];

export function extractBrandFromName(name: string): string {
  const words = name.split(/\s+/);
  for (const word of words) {
    const clean = word.replace(/[^a-zA-Z-]/g, "");
    if (
      clean.length >= 2 &&
      ALL_BRANDS.some((b) => b.toLowerCase() === clean.toLowerCase())
    ) {
      return clean;
    }
  }
  return "";
}

export function normalize(text: string): string {
  return text.toLowerCase().replace(/\s+/g, " ").trim();
}

export function normalizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9\s]/g, "").replace(/\s+/g, " ")
    .trim();
}

export function hashCode(str: string): string {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash).toString(36);
}
