export interface ModelEntry {
  key: string;
  brand: string;
  display: string;
  soc?: string;
  panel?: "AMOLED" | "pOLED" | "IPS LCD" | "PLS LCD" | "TFT LCD";
  inches?: number;
  refreshHz?: number;
  resolution?: "HD+" | "FHD+" | "QHD+";
  batteryMah?: number;
  chargingW?: number;
  mainCameraMp?: number;
  ois?: boolean;
  ipRating?: string;
  nfc?: boolean;
  stereoSpeakers?: boolean;
  headphoneJack?: boolean;
  releaseYear?: number;
  osUpgrades?: number;
  confidence: "high" | "medium" | "low";
  aliases?: string[];
}

export const PHONE_MODELS: ModelEntry[] = [
  {
    key: "realme narzo 90x 5g",
    brand: "realme",
    display: "realme Narzo 90x 5G",
    soc: "Dimensity 6300",
    panel: "IPS LCD",
    inches: 6.8,
    refreshHz: 144,
    resolution: "HD+",
    batteryMah: 7000,
    chargingW: 60,
    mainCameraMp: 50,
    ois: false,
    ipRating: "IP65",
    releaseYear: 2025,
    confidence: "high",
    aliases: ["narzo 90x"],
  },
  {
    key: "realme narzo 100 lite 5g",
    brand: "realme",
    display: "realme Narzo 100 Lite 5G",
    soc: "Dimensity 6300",
    resolution: "HD+",
    mainCameraMp: 50,
    releaseYear: 2026,
    confidence: "medium",
    aliases: ["narzo 100 lite"],
  },
  {
    key: "redmi a7 pro 5g",
    brand: "Xiaomi",
    display: "Redmi A7 Pro 5G",
    soc: "Unisoc T8300",
    panel: "IPS LCD",
    inches: 6.9,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 6300,
    chargingW: 15,
    mainCameraMp: 32,
    ois: false,
    releaseYear: 2026,
    confidence: "high",
  },
  {
    key: "redmi a7 pro 4g",
    brand: "Xiaomi",
    display: "Redmi A7 Pro 4G",
    soc: "Unisoc T7250",
    panel: "IPS LCD",
    inches: 6.9,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 6300,
    chargingW: 15,
    mainCameraMp: 13,
    ois: false,
    releaseYear: 2026,
    confidence: "high",
  },
  {
    key: "redmi a7",
    brand: "Xiaomi",
    display: "Redmi A7",
    soc: "Unisoc T7250",
    panel: "IPS LCD",
    inches: 6.88,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5200,
    chargingW: 15,
    mainCameraMp: 13,
    ois: false,
    releaseYear: 2026,
    confidence: "high",
  },
  {
    key: "samsung galaxy m17 5g",
    brand: "Samsung",
    display: "Samsung Galaxy M17 5G",
    soc: "Exynos 1330",
    panel: "AMOLED",
    inches: 6.65,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    ois: true,
    releaseYear: 2025,
    osUpgrades: 6,
    confidence: "high",
    aliases: ["galaxy m17"],
  },
  {
    key: "samsung galaxy f17 5g",
    brand: "Samsung",
    display: "Samsung Galaxy F17 5G",
    soc: "Exynos 1330",
    panel: "AMOLED",
    inches: 6.65,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    ois: true,
    releaseYear: 2025,
    osUpgrades: 6,
    confidence: "high",
    aliases: ["galaxy f17"],
  },
  {
    key: "poco m7 plus",
    brand: "POCO",
    display: "POCO M7 Plus",
    soc: "Snapdragon 6s Gen 3",
    panel: "IPS LCD",
    inches: 6.9,
    refreshHz: 144,
    resolution: "HD+",
    batteryMah: 7000,
    chargingW: 33,
    mainCameraMp: 50,
    ois: false,
    releaseYear: 2025,
    confidence: "high",
  },
  {
    key: "motorola g35 5g",
    brand: "Motorola",
    display: "Motorola G35 5G",
    soc: "Unisoc T760",
    panel: "IPS LCD",
    inches: 6.72,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 18,
    mainCameraMp: 50,
    ois: false,
    releaseYear: 2024,
    confidence: "medium",
    aliases: ["moto g35 5g", "moto g35"],
  },
  {
    key: "poco m7 5g",
    brand: "POCO",
    display: "POCO M7 5G",
    soc: "Snapdragon 4 Gen 2",
    panel: "IPS LCD",
    inches: 6.88,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5160,
    chargingW: 18,
    mainCameraMp: 50,
    ois: false,
    ipRating: "IP64",
    nfc: false,
    headphoneJack: true,
    releaseYear: 2025,
    confidence: "high",
  },
  {
    key: "poco m7 pro 5g",
    brand: "POCO",
    display: "POCO M7 Pro 5G",
    soc: "Dimensity 7025",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5110,
    chargingW: 45,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP64",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2025,
    confidence: "high",
  },
  {
    key: "poco c75 5g",
    brand: "POCO",
    display: "POCO C75 5G",
    soc: "Snapdragon 4s Gen 2",
    panel: "IPS LCD",
    inches: 6.88,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5160,
    chargingW: 18,
    mainCameraMp: 50,
    ois: false,
    headphoneJack: true,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "poco m6 pro 5g",
    brand: "POCO",
    display: "POCO M6 Pro 5G",
    soc: "Snapdragon 4 Gen 2",
    panel: "IPS LCD",
    inches: 6.79,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 18,
    mainCameraMp: 50,
    releaseYear: 2023,
    confidence: "high",
  },
  {
    key: "redmi 14c 5g",
    brand: "Xiaomi",
    display: "Redmi 14C 5G",
    soc: "Snapdragon 4s Gen 2",
    panel: "IPS LCD",
    inches: 6.88,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5160,
    chargingW: 18,
    mainCameraMp: 50,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "redmi 14c",
    brand: "Xiaomi",
    display: "Redmi 14C",
    soc: "Helio G81",
    panel: "IPS LCD",
    inches: 6.88,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5160,
    chargingW: 18,
    mainCameraMp: 50,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "redmi a4 5g",
    brand: "Xiaomi",
    display: "Redmi A4 5G",
    soc: "Snapdragon 4s Gen 2",
    panel: "IPS LCD",
    inches: 6.88,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5160,
    chargingW: 18,
    mainCameraMp: 50,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "redmi note 14 5g",
    brand: "Xiaomi",
    display: "Redmi Note 14 5G",
    soc: "Dimensity 7025",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5110,
    chargingW: 45,
    mainCameraMp: 108,
    ois: true,
    ipRating: "IP64",
    nfc: true,
    releaseYear: 2025,
    confidence: "high",
  },
  {
    key: "redmi note 13 5g",
    brand: "Xiaomi",
    display: "Redmi Note 13 5G",
    soc: "Dimensity 6080",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 33,
    mainCameraMp: 108,
    releaseYear: 2024,
    confidence: "high",
  },

  {
    key: "samsung galaxy m06 5g",
    brand: "Samsung",
    display: "Samsung Galaxy M06 5G",
    soc: "Dimensity 6300",
    panel: "PLS LCD",
    inches: 6.7,
    refreshHz: 90,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    releaseYear: 2025,
    osUpgrades: 4,
    confidence: "high",
    aliases: ["samsung m06 5g", "galaxy m06 5g"],
  },
  {
    key: "samsung galaxy m07",
    brand: "Samsung",
    display: "Samsung Galaxy M07",
    soc: "Helio G99",
    panel: "PLS LCD",
    inches: 6.7,
    refreshHz: 90,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    releaseYear: 2025,
    osUpgrades: 4,
    confidence: "low",
    aliases: ["galaxy m07"],
  },
  {
    key: "samsung galaxy f07",
    brand: "Samsung",
    display: "Samsung Galaxy F07",
    soc: "Helio G99",
    panel: "PLS LCD",
    inches: 6.7,
    refreshHz: 90,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    releaseYear: 2025,
    osUpgrades: 4,
    confidence: "high",
    aliases: ["galaxy f07"],
  },
  {
    key: "samsung galaxy m15 5g",
    brand: "Samsung",
    display: "Samsung Galaxy M15 5G",
    soc: "Dimensity 6100+",
    panel: "AMOLED",
    inches: 6.5,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 6000,
    chargingW: 25,
    mainCameraMp: 50,
    releaseYear: 2024,
    osUpgrades: 4,
    confidence: "high",
  },
  {
    key: "samsung galaxy a15 5g",
    brand: "Samsung",
    display: "Samsung Galaxy A15 5G",
    soc: "Dimensity 6100+",
    panel: "AMOLED",
    inches: 6.5,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    releaseYear: 2024,
    osUpgrades: 4,
    confidence: "high",
  },
  {
    key: "samsung galaxy m14 5g",
    brand: "Samsung",
    display: "Samsung Galaxy M14 5G",
    soc: "Exynos 1330",
    panel: "PLS LCD",
    inches: 6.6,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 6000,
    chargingW: 25,
    mainCameraMp: 50,
    releaseYear: 2023,
    confidence: "high",
  },
  {
    key: "samsung galaxy m35 5g",
    brand: "Samsung",
    display: "Samsung Galaxy M35 5G",
    soc: "Exynos 1380",
    panel: "AMOLED",
    inches: 6.6,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 6000,
    chargingW: 25,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP67",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    osUpgrades: 4,
    confidence: "high",
  },

  {
    key: "realme narzo 80 lite 4g",
    brand: "realme",
    display: "realme Narzo 80 Lite 4G",
    soc: "Unisoc T7250",
    panel: "IPS LCD",
    inches: 6.74,
    refreshHz: 90,
    resolution: "HD+",
    batteryMah: 6300,
    chargingW: 15,
    mainCameraMp: 13,
    ois: false,
    ipRating: "IP54",
    releaseYear: 2025,
    confidence: "high",
  },
  {
    key: "realme narzo 80 lite",
    brand: "realme",
    display: "realme Narzo 80 Lite",
    soc: "Dimensity 6300",
    panel: "IPS LCD",
    inches: 6.67,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 6000,
    chargingW: 15,
    mainCameraMp: 32,
    ois: false,
    releaseYear: 2025,
    confidence: "high",
  },
  {
    key: "realme p3 lite 5g",
    brand: "realme",
    display: "realme P3 Lite 5G",
    soc: "Dimensity 6300",
    panel: "IPS LCD",
    inches: 6.67,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 6000,
    chargingW: 45,
    mainCameraMp: 32,
    ipRating: "IP64",
    releaseYear: 2025,
    confidence: "medium",
  },
  {
    key: "realme narzo 70x 5g",
    brand: "realme",
    display: "realme narzo 70x 5G",
    soc: "Dimensity 6100+",
    panel: "IPS LCD",
    inches: 6.72,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 45,
    mainCameraMp: 50,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "realme p1 5g",
    brand: "realme",
    display: "realme P1 5G",
    soc: "Dimensity 7050",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 45,
    mainCameraMp: 50,
    releaseYear: 2024,
    confidence: "high",
  },

  {
    key: "motorola g45 5g",
    brand: "Motorola",
    display: "Motorola G45 5G",
    soc: "Snapdragon 6s Gen 3",
    panel: "IPS LCD",
    inches: 6.5,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 18,
    mainCameraMp: 50,
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
    aliases: ["moto g45 5g"],
  },
  {
    key: "motorola g85 5g",
    brand: "Motorola",
    display: "Motorola G85 5G",
    soc: "Snapdragon 6s Gen 3",
    panel: "pOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 33,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP52",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
    aliases: ["moto g85 5g"],
  },

  {
    key: "iqoo z10 lite 5g",
    brand: "iQOO",
    display: "iQOO Z10 Lite 5G",
    soc: "Dimensity 6300",
    panel: "IPS LCD",
    inches: 6.74,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 6000,
    chargingW: 15,
    mainCameraMp: 50,
    ipRating: "IP64",
    releaseYear: 2025,
    confidence: "medium",
  },
  {
    key: "iqoo z9x 5g",
    brand: "iQOO",
    display: "iQOO Z9x 5G",
    soc: "Snapdragon 6 Gen 1",
    panel: "IPS LCD",
    inches: 6.72,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 6000,
    chargingW: 44,
    mainCameraMp: 50,
    releaseYear: 2024,
    confidence: "high",
  },

  {
    key: "infinix hot 50 5g",
    brand: "Infinix",
    display: "Infinix Hot 50 5G",
    soc: "Dimensity 6300",
    panel: "IPS LCD",
    inches: 6.7,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 18,
    mainCameraMp: 48,
    releaseYear: 2024,
    confidence: "medium",
  },

  {
    key: "lava blaze duo 5g",
    brand: "LAVA",
    display: "LAVA Blaze Duo 5G",
    soc: "Dimensity 7025",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 33,
    mainCameraMp: 64,
    releaseYear: 2024,
    confidence: "medium",
  },

  {
    key: "redmi note 13 pro 5g",
    brand: "Xiaomi",
    display: "Redmi Note 13 Pro 5G",
    soc: "Snapdragon 7s Gen 2",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5100,
    chargingW: 67,
    mainCameraMp: 200,
    ois: true,
    ipRating: "IP54",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "redmi note 13 pro+ 5g",
    brand: "Xiaomi",
    display: "Redmi Note 13 Pro+ 5G",
    soc: "Dimensity 7200",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 120,
    mainCameraMp: 200,
    ois: true,
    ipRating: "IP68",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
    aliases: ["redmi note 13 pro plus 5g"],
  },
  {
    key: "redmi note 12 5g",
    brand: "Xiaomi",
    display: "Redmi Note 12 5G",
    soc: "Snapdragon 4 Gen 1",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 33,
    mainCameraMp: 48,
    releaseYear: 2023,
    confidence: "high",
  },
  {
    key: "redmi 13c",
    brand: "Xiaomi",
    display: "Redmi 13C",
    soc: "Helio G85",
    panel: "IPS LCD",
    inches: 6.74,
    refreshHz: 90,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 18,
    mainCameraMp: 50,
    releaseYear: 2023,
    confidence: "high",
  },
  {
    key: "redmi 13c 5g",
    brand: "Xiaomi",
    display: "Redmi 13C 5G",
    soc: "Dimensity 6100+",
    panel: "IPS LCD",
    inches: 6.74,
    refreshHz: 90,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 18,
    mainCameraMp: 50,
    releaseYear: 2023,
    confidence: "high",
  },
  {
    key: "poco x6 5g",
    brand: "POCO",
    display: "POCO X6 5G",
    soc: "Snapdragon 7s Gen 2",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5100,
    chargingW: 67,
    mainCameraMp: 64,
    ois: true,
    ipRating: "IP54",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "poco x6 pro 5g",
    brand: "POCO",
    display: "POCO X6 Pro 5G",
    soc: "Dimensity 8300 Ultra",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 67,
    mainCameraMp: 64,
    ois: true,
    ipRating: "IP54",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "poco x7 pro 5g",
    brand: "POCO",
    display: "POCO X7 Pro 5G",
    soc: "Dimensity 8400 Ultra",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 6550,
    chargingW: 90,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP68",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2025,
    confidence: "medium",
  },
  {
    key: "poco m6 5g",
    brand: "POCO",
    display: "POCO M6 5G",
    soc: "Dimensity 6100+",
    panel: "IPS LCD",
    inches: 6.74,
    refreshHz: 90,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 18,
    mainCameraMp: 50,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "poco c65",
    brand: "POCO",
    display: "POCO C65",
    soc: "Helio G85",
    panel: "IPS LCD",
    inches: 6.74,
    refreshHz: 90,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 18,
    mainCameraMp: 50,
    releaseYear: 2023,
    confidence: "high",
  },

  {
    key: "samsung galaxy m34 5g",
    brand: "Samsung",
    display: "Samsung Galaxy M34 5G",
    soc: "Exynos 1280",
    panel: "AMOLED",
    inches: 6.5,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 6000,
    chargingW: 25,
    mainCameraMp: 50,
    ois: true,
    nfc: true,
    releaseYear: 2023,
    osUpgrades: 4,
    confidence: "high",
  },
  {
    key: "samsung galaxy a14 5g",
    brand: "Samsung",
    display: "Samsung Galaxy A14 5G",
    soc: "Exynos 1330",
    panel: "PLS LCD",
    inches: 6.6,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 15,
    mainCameraMp: 50,
    releaseYear: 2023,
    osUpgrades: 4,
    confidence: "high",
  },
  {
    key: "samsung galaxy a16 5g",
    brand: "Samsung",
    display: "Samsung Galaxy A16 5G",
    soc: "Dimensity 6300",
    panel: "AMOLED",
    inches: 6.7,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    ipRating: "IP54",
    nfc: true,
    releaseYear: 2024,
    osUpgrades: 6,
    confidence: "medium",
  },
  {
    key: "samsung galaxy a25 5g",
    brand: "Samsung",
    display: "Samsung Galaxy A25 5G",
    soc: "Exynos 1280",
    panel: "AMOLED",
    inches: 6.5,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    ois: true,
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    osUpgrades: 4,
    confidence: "high",
  },
  {
    key: "samsung galaxy a35 5g",
    brand: "Samsung",
    display: "Samsung Galaxy A35 5G",
    soc: "Exynos 1380",
    panel: "AMOLED",
    inches: 6.6,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP67",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    osUpgrades: 4,
    confidence: "high",
  },
  {
    key: "samsung galaxy a55 5g",
    brand: "Samsung",
    display: "Samsung Galaxy A55 5G",
    soc: "Exynos 1480",
    panel: "AMOLED",
    inches: 6.6,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 25,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP67",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    osUpgrades: 4,
    confidence: "high",
  },
  {
    key: "samsung galaxy f15 5g",
    brand: "Samsung",
    display: "Samsung Galaxy F15 5G",
    soc: "Dimensity 6100+",
    panel: "AMOLED",
    inches: 6.5,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 6000,
    chargingW: 25,
    mainCameraMp: 50,
    releaseYear: 2024,
    osUpgrades: 4,
    confidence: "high",
  },
  {
    key: "samsung galaxy m55 5g",
    brand: "Samsung",
    display: "Samsung Galaxy M55 5G",
    soc: "Snapdragon 7 Gen 1",
    panel: "AMOLED",
    inches: 6.7,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 45,
    mainCameraMp: 50,
    ois: true,
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    osUpgrades: 4,
    confidence: "medium",
  },

  {
    key: "realme 12 pro 5g",
    brand: "realme",
    display: "realme 12 Pro 5G",
    soc: "Snapdragon 6 Gen 1",
    panel: "AMOLED",
    inches: 6.7,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 67,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP65",
    nfc: true,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "realme narzo 70 pro 5g",
    brand: "realme",
    display: "realme narzo 70 Pro 5G",
    soc: "Dimensity 7050",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 67,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP54",
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "realme c67 5g",
    brand: "realme",
    display: "realme C67 5G",
    soc: "Dimensity 6100+",
    panel: "IPS LCD",
    inches: 6.72,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 33,
    mainCameraMp: 50,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "realme c55",
    brand: "realme",
    display: "realme C55",
    soc: "Helio G88",
    panel: "IPS LCD",
    inches: 6.72,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 33,
    mainCameraMp: 64,
    releaseYear: 2023,
    confidence: "high",
  },
  {
    key: "realme p1 pro 5g",
    brand: "realme",
    display: "realme P1 Pro 5G",
    soc: "Snapdragon 6 Gen 1",
    panel: "AMOLED",
    inches: 6.7,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 45,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP65",
    releaseYear: 2024,
    confidence: "medium",
  },

  {
    key: "iqoo z9 5g",
    brand: "iQOO",
    display: "iQOO Z9 5G",
    soc: "Dimensity 7200",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 44,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP54",
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "vivo t3 5g",
    brand: "vivo",
    display: "vivo T3 5G",
    soc: "Dimensity 7200",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 44,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP54",
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "vivo t2 5g",
    brand: "vivo",
    display: "vivo T2 5G",
    soc: "Snapdragon 695",
    panel: "AMOLED",
    inches: 6.38,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 4500,
    chargingW: 44,
    mainCameraMp: 64,
    releaseYear: 2023,
    confidence: "high",
  },

  {
    key: "motorola g34 5g",
    brand: "Motorola",
    display: "Motorola G34 5G",
    soc: "Snapdragon 695",
    panel: "IPS LCD",
    inches: 6.5,
    refreshHz: 120,
    resolution: "HD+",
    batteryMah: 5000,
    chargingW: 20,
    mainCameraMp: 50,
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
    aliases: ["moto g34 5g"],
  },
  {
    key: "motorola g54 5g",
    brand: "Motorola",
    display: "Motorola G54 5G",
    soc: "Dimensity 7020",
    panel: "IPS LCD",
    inches: 6.5,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 6000,
    chargingW: 33,
    mainCameraMp: 50,
    ois: true,
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2023,
    confidence: "high",
    aliases: ["moto g54 5g"],
  },
  {
    key: "motorola g64 5g",
    brand: "Motorola",
    display: "Motorola G64 5G",
    soc: "Dimensity 7025",
    panel: "IPS LCD",
    inches: 6.5,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 6000,
    chargingW: 33,
    mainCameraMp: 50,
    ois: true,
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
    aliases: ["moto g64 5g"],
  },
  {
    key: "motorola edge 50 fusion",
    brand: "Motorola",
    display: "Motorola Edge 50 Fusion",
    soc: "Snapdragon 7s Gen 2",
    panel: "pOLED",
    inches: 6.7,
    refreshHz: 144,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 68,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP68",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    confidence: "high",
    aliases: ["moto edge 50 fusion"],
  },

  {
    key: "oneplus nord ce 3 lite 5g",
    brand: "OnePlus",
    display: "OnePlus Nord CE 3 Lite 5G",
    soc: "Snapdragon 695",
    panel: "IPS LCD",
    inches: 6.72,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 67,
    mainCameraMp: 108,
    releaseYear: 2023,
    confidence: "high",
  },
  {
    key: "oneplus nord ce 4 lite 5g",
    brand: "OnePlus",
    display: "OnePlus Nord CE 4 Lite 5G",
    soc: "Snapdragon 695",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5500,
    chargingW: 80,
    mainCameraMp: 50,
    ois: true,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "oneplus nord ce 4 5g",
    brand: "OnePlus",
    display: "OnePlus Nord CE 4 5G",
    soc: "Snapdragon 7 Gen 3",
    panel: "AMOLED",
    inches: 6.7,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5500,
    chargingW: 100,
    mainCameraMp: 50,
    ois: true,
    releaseYear: 2024,
    confidence: "high",
  },
  {
    key: "nothing phone 2a",
    brand: "Nothing",
    display: "Nothing Phone (2a)",
    soc: "Dimensity 7200",
    panel: "AMOLED",
    inches: 6.7,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 45,
    mainCameraMp: 50,
    ois: true,
    ipRating: "IP54",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    osUpgrades: 3,
    confidence: "high",
    aliases: ["nothing phone (2a)"],
  },
  {
    key: "cmf phone 1",
    brand: "Nothing",
    display: "CMF Phone 1",
    soc: "Dimensity 7300",
    panel: "AMOLED",
    inches: 6.67,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 5000,
    chargingW: 33,
    mainCameraMp: 50,
    ipRating: "IP52",
    nfc: true,
    releaseYear: 2024,
    osUpgrades: 2,
    confidence: "high",
  },

  {
    key: "google pixel 7a",
    brand: "Google",
    display: "Google Pixel 7a",
    soc: "Tensor G2",
    panel: "AMOLED",
    inches: 6.1,
    refreshHz: 90,
    resolution: "FHD+",
    batteryMah: 4385,
    chargingW: 18,
    mainCameraMp: 64,
    ois: true,
    ipRating: "IP67",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2023,
    osUpgrades: 3,
    confidence: "high",
    aliases: ["pixel 7a"],
  },
  {
    key: "google pixel 8a",
    brand: "Google",
    display: "Google Pixel 8a",
    soc: "Tensor G3",
    panel: "AMOLED",
    inches: 6.1,
    refreshHz: 120,
    resolution: "FHD+",
    batteryMah: 4492,
    chargingW: 18,
    mainCameraMp: 64,
    ois: true,
    ipRating: "IP67",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2024,
    osUpgrades: 7,
    confidence: "high",
    aliases: ["pixel 8a"],
  },
  {
    key: "iphone 13",
    brand: "Apple",
    display: "Apple iPhone 13",
    soc: "Apple A15 Bionic",
    panel: "AMOLED",
    inches: 6.1,
    refreshHz: 60,
    resolution: "FHD+",
    batteryMah: 3240,
    chargingW: 20,
    mainCameraMp: 12,
    ois: true,
    ipRating: "IP68",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2021,
    confidence: "high",
  },
  {
    key: "iphone 15",
    brand: "Apple",
    display: "Apple iPhone 15",
    soc: "Apple A16 Bionic",
    panel: "AMOLED",
    inches: 6.1,
    refreshHz: 60,
    resolution: "FHD+",
    batteryMah: 3349,
    chargingW: 20,
    mainCameraMp: 48,
    ois: true,
    ipRating: "IP68",
    nfc: true,
    stereoSpeakers: true,
    releaseYear: 2023,
    confidence: "high",
  },
];

const MODEL_INDEX = new Map<string, ModelEntry>();
for (const m of PHONE_MODELS) {
  MODEL_INDEX.set(m.key, m);
  for (const a of m.aliases ?? []) MODEL_INDEX.set(a, m);
}

const MODEL_KEYS = [...MODEL_INDEX.keys()].sort((a, b) => b.length - a.length);

export function lookupModel(text: string): ModelEntry | null {
  if (!text) return null;
  const hay = ` ${
    text.toLowerCase().replace(/[^a-z0-9+]+/g, " ").replace(/\s+/g, " ").trim()
  } `;
  for (const key of MODEL_KEYS) {
    if (hay.includes(` ${key} `)) return MODEL_INDEX.get(key)!;
  }
  return null;
}
